// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsftcjvytowdvqqeaofa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzZnRjanZ5dG93ZHZxcWVhb2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTgwODgsImV4cCI6MjA1OTM3NDA4OH0.2EEwW_44yAFDzS7bKxyd_-rmZDGKe8XiO2gglNUadA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);